package com.xo.mbg.mapper;

import com.xo.mbg.model.UmsAdminPermissionRelation;

public interface UmsAdminPermissionRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbg.generated
     */
    int insert(UmsAdminPermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbg.generated
     */
    int insertSelective(UmsAdminPermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbg.generated
     */
    UmsAdminPermissionRelation selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UmsAdminPermissionRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_admin_permission_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UmsAdminPermissionRelation record);
}